### ISSUE TITLE
TbJsonGridView -  Parser error!

### ISSUE THREAD

**Issue by khirod** [clevertech/YiiBooster#190]
Hi.

we are using TbJsonGridView but it  return a Parser error! on a alert  when some body click on page number for pagination ,search ,sort link  , Please guide us How to fix this , Code are  as follows:

``` php
$this->widget('bootstrap.widgets.TbJsonGridView', array(
    'dataProvider' => $model->search(),
    'filter' => $model,
    'type' => 'striped bordered condensed',
    'json' => true,
    //'ajaxUpdate' => true,
    'summaryText' => false,
    'cacheTTL' => 10, // cache will be stored 10 seconds (see cacheTTLType)
    'cacheTTLType' => 's', // type can be of seconds, minutes or hours
    'columns' => array(
        'id_feedback',
        'feedback',
        'felkod',
        array(
            //'header' => Yii::t('ses', 'Action'),
            'class' => 'bootstrap.widgets.TbJsonButtonColumn',
            'template' => '{view} {update}',


        ),
    ),

));
```

![TbJsonGridViewerror](https://f.cloud.github.com/assets/708301/15151/399ad3d4-4703-11e2-9022-377b6979a9c0.png)

**Comment by pc-carm** [comment]
Hello, plase note I'm not a JS/HTML/CSS/Yii expert. I started playing around with this widget and I have the same problem as @prawee and @onesource4u about the grid sorting just once. It also doesn't seem to filter the fields when typing the text in the filters and then pressing Enter, while everything in the example at the official page seems to work fine.
I don't know about the view/delete buttons yet because I haven't tested them.
