### ISSUE TITLE
BS3 - init

### ISSUE THREAD

**Issue by amrbedair** [clevertech/YiiBooster#794]
- include bootstrap 3.1.1
- adjust some widgets
- new doc site - stating the changes made -
- moving the old site to a new url - pointing to it from the new one -
- not final code structure, and method signatures

**Comment by iseus** [comment]
Hi,

@amrbedair, you changed TbEditableDetailView to extend CDetailView instead of TbDetailView, meanwhile you forced the default css classed inside the init:
$this->htmlOptions = array('class'=> 'table table-bordered table-striped table-hover');
After that you left this part undocumented, how to change or workaround this issue.

So you left no option to change it. Before this 'update' there were an option to set anything from 'type' attribute at least.

Setting back class definition to extend TbDetailView again, and commenting out the forced htmlOptions in the init wouldn't break anything as I see. This version is a very poor design.
